package com.ztb.studentTest.model;

import java.util.Set;



/**°à¼¶±í
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Grade  implements java.io.Serializable {


    // Fields    

     private Long gradeId;
     private String gradeName;
     private Integer delFlag;
     private Set students;


    // Constructors



	/** default constructor */
    public Grade() {
    }



    public Integer getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    public Long getGradeId() {
        return gradeId;
    }

    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    public String getGradeName() {
        return gradeName;
    }

    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }



    public Set getStudents() {
        return students;
    }



    public void setStudents(Set students) {
        this.students = students;
    }
    
    








}